
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Adding an Exception &#8212; Friendly tracebacks 0.0.3 documentation</title>
    <link rel="stylesheet" href="_static/sphinxdoc.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    <script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <script type="text/javascript" src="_static/language_data.js"></script>
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
    <link rel="next" title="Friendly tracebacks - in English" href="tracebacks_en.html" />
    <link rel="prev" title="Some thoughts on the design of friendly-traceback" href="design.html" /> 
  </head><body>
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="tracebacks_en.html" title="Friendly tracebacks - in English"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="design.html" title="Some thoughts on the design of friendly-traceback"
             accesskey="P">previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="index.html">Friendly tracebacks 0.0.3 documentation</a> &#187;</li> 
      </ul>
    </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h3><a href="index.html">Table of Contents</a></h3>
  <ul>
<li><a class="reference internal" href="#">Adding an Exception</a><ul>
<li><a class="reference internal" href="#adding-a-test-case">Adding a test case</a><ul>
<li><a class="reference internal" href="#raising-an-exception">Raising an exception</a></li>
<li><a class="reference internal" href="#catching-an-exception">Catching an exception</a></li>
</ul>
</li>
<li><a class="reference internal" href="#adding-generic-information">Adding generic information</a></li>
<li><a class="reference internal" href="#add-specific-information">Add specific information</a></li>
<li><a class="reference internal" href="#test-your-work">Test your work</a></li>
<li><a class="reference internal" href="#make-a-pull-request">Make a pull request</a></li>
<li><a class="reference internal" href="#adding-to-an-existing-exception">Adding to an existing exception</a></li>
</ul>
</li>
</ul>

  <h4>Previous topic</h4>
  <p class="topless"><a href="design.html"
                        title="previous chapter">Some thoughts on the design of friendly-traceback</a></p>
  <h4>Next topic</h4>
  <p class="topless"><a href="tracebacks_en.html"
                        title="next chapter">Friendly tracebacks - in English</a></p>
  <div role="note" aria-label="source link">
    <h3>This Page</h3>
    <ul class="this-page-menu">
      <li><a href="_sources/adding_exception.rst.txt"
            rel="nofollow">Show Source</a></li>
    </ul>
   </div>
<div id="searchbox" style="display: none" role="search">
  <h3>Quick search</h3>
    <div class="searchformwrapper">
    <form class="search" action="search.html" method="get">
      <input type="text" name="q" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    </div>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <div class="section" id="adding-an-exception">
<h1>Adding an Exception<a class="headerlink" href="#adding-an-exception" title="Permalink to this headline">¶</a></h1>
<div class="admonition warning">
<p class="first admonition-title">Warning</p>
<p class="last">Doing a task such as described here assumes that you are only adding to the existing code, mostly in the form of
additions of test files and functions in two other files.
Assuming this is the case, you can work directly from the
masters branch, without needing to add a separate branch.
Of course, you may create a separate branch if you prefer
to do so; its name should be based on the issue number that
you create.</p>
</div>
<p>This primarily describes the situation where you wish to add friendly
tracebacks for an Exception that is not already included.
Cases where an already included Exception is found to have
possible different causes, such as <code class="docutils literal notranslate"><span class="pre">IndentationError</span></code>,
but which are not properly taken care of by the existing code
are covered near the end of this document.</p>
<div class="admonition note">
<p class="first admonition-title">Note</p>
<p><strong>Checklist</strong></p>
<p>The following are the required steps before a pull request.
Each item is explained in a different section below. If you find
the instructions unclear, please do not hesitate to reach out.</p>
<blockquote>
<div><ul class="simple">
<li>File an issue indicating that you are planning to work on a
given exception.</li>
<li><dl class="first docutils">
<dt>Add test case</dt>
<dd><ul class="first last">
<li>Add raise_some_exception.py file</li>
<li>Add catch_some_exception.py file</li>
</ul>
</dd>
</dl>
</li>
<li>Add generic information</li>
<li>Add specific information</li>
<li>Execute catch_some_exception.py and confirm visually it works as expected</li>
<li>Run pytest and confirm that your new test is included</li>
<li>Make a pull request</li>
</ul>
</div></blockquote>
<p>The following are optional steps; they will need to be done at some point
but, apart for possible translations in languages other than French,
I can definitely take care of this.</p>
<blockquote class="last">
<div><ul class="simple">
<li><dl class="first docutils">
<dt>Add case to tests/tb_common.py</dt>
<dd><ul class="first last">
<li>Run tests/tb_english.py and ensure docs/tracebacks_en.rst shows
the expected result</li>
</ul>
</dd>
</dl>
</li>
<li>Run make_tb.bat or do the equivalent on non Windows computer</li>
<li>Confirm that all docs/tracebacks_xx.rst include the new exception</li>
<li>Add translation</li>
</ul>
</div></blockquote>
</div>
<div class="section" id="adding-a-test-case">
<h2>Adding a test case<a class="headerlink" href="#adding-a-test-case" title="Permalink to this headline">¶</a></h2>
<p>After you have filed an issue indicating that you wished to
adding coverage for an exception that is not previously
covered, you need to start by adding a test case.
As an example throughout, I will use the existing one for
<code class="docutils literal notranslate"><span class="pre">NameError</span></code>.</p>
<div class="section" id="raising-an-exception">
<h3>Raising an exception<a class="headerlink" href="#raising-an-exception" title="Permalink to this headline">¶</a></h3>
<p>Your test file name should start with <code class="docutils literal notranslate"><span class="pre">raise_</span></code>,
such as <code class="docutils literal notranslate"><span class="pre">raise_name_error.py</span></code>.  Here is the content of that file:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="sd">&quot;&quot;&quot;Contains a function that should raise NameError&quot;&quot;&quot;</span>

<span class="k">def</span> <span class="nf">test</span><span class="p">():</span>
    <span class="sd">&quot;&quot;&quot;Should raise NameError&quot;&quot;&quot;</span>
    <span class="n">b</span> <span class="o">=</span> <span class="n">c</span>
    <span class="n">d</span> <span class="o">=</span> <span class="mi">3</span>

<span class="k">if</span> <span class="vm">__name__</span> <span class="o">==</span> <span class="s2">&quot;__main__&quot;</span><span class="p">:</span>
    <span class="kn">import</span> <span class="nn">friendly_traceback</span>
    <span class="n">friendly_traceback</span><span class="o">.</span><span class="n">install</span><span class="p">()</span>
    <span class="n">test</span><span class="p">()</span>
</pre></div>
</div>
<p>As you can see, it contains a single test function which, when run,
would generate the expected exception.
Note that we do not use an artificial <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">NameError</span></code> statement,
but a genuine example. This is important as we want the recorded
traceback to reflect what users might encounter in their own programs.</p>
<p>After creating this file, you should run it from the root
directory of this repository, with something like:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">python</span> <span class="n">tests</span><span class="o">/</span><span class="n">raise_name_error</span><span class="o">.</span><span class="n">py</span>
</pre></div>
</div>
<p>Assuming that your OS default language is either English, or a
language for which translations do not exists, the output should look something like the following:</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    MyException: Some informative message

No information is known about this exception.


Execution stopped on line 13 of file &#39;raise_unknown_error.py&#39;.

   10: if __name__ == &quot;__main__&quot;:
   11:     import friendly_traceback
   12:     friendly_traceback.install()
--&gt;13:     test()

Exception raised on line 8 of file &#39;raise_unknown_error.py&#39;.

    6:
    7: def test():
--&gt; 8:     raise MyException(&quot;Some informative message&quot;)
    9:
</pre></div>
</div>
<p>If this is the case, you are ready to go to the next step.</p>
</div>
<div class="section" id="catching-an-exception">
<h3>Catching an exception<a class="headerlink" href="#catching-an-exception" title="Permalink to this headline">¶</a></h3>
<p>Now that you can run a script that can raise an exception,
you need to create a script that will catch it, and can
also be used by pytest which we use as our test runner.
Here’s the content of <code class="docutils literal notranslate"><span class="pre">catch_name_error.py</span></code>, with some
numbered comments added, to which we refer below:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">friendly_traceback</span>  <span class="c1"># 1</span>
<span class="kn">import</span> <span class="nn">sys</span>

<span class="k">def</span> <span class="nf">test_name_error</span><span class="p">():</span>  <span class="c1"># 2</span>
    <span class="k">try</span><span class="p">:</span>                <span class="c1"># 3</span>
        <span class="kn">from</span> <span class="nn">.</span> <span class="k">import</span> <span class="n">raise_name_error</span>  <span class="c1"># for pytest</span>
    <span class="k">except</span> <span class="ne">ImportError</span><span class="p">:</span>
        <span class="kn">import</span> <span class="nn">raise_name_error</span>

    <span class="k">try</span><span class="p">:</span>
        <span class="n">raise_name_error</span><span class="o">.</span><span class="n">test</span><span class="p">()</span>  <span class="c1"># 4</span>
    <span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
        <span class="n">friendly_traceback</span><span class="o">.</span><span class="n">explain</span><span class="p">(</span><span class="o">*</span><span class="n">sys</span><span class="o">.</span><span class="n">exc_info</span><span class="p">(),</span> <span class="n">redirect</span><span class="o">=</span><span class="s2">&quot;capture&quot;</span><span class="p">)</span>      <span class="c1"># 5</span>
    <span class="n">result</span> <span class="o">=</span> <span class="n">friendly_traceback</span><span class="o">.</span><span class="n">get_output</span><span class="p">()</span>  <span class="c1"># 6</span>
    <span class="k">assert</span> <span class="s2">&quot;NameError: name &#39;c&#39; is not defined&quot;</span> <span class="ow">in</span> <span class="n">result</span>  <span class="c1"># 7</span>
    <span class="k">return</span> <span class="n">result</span>  <span class="c1"># 8</span>


<span class="k">if</span> <span class="vm">__name__</span> <span class="o">==</span> <span class="s2">&quot;__main__&quot;</span><span class="p">:</span>      <span class="c1"># 9</span>
    <span class="n">result</span> <span class="o">=</span> <span class="n">test_name_error</span><span class="p">()</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">result</span><span class="p">)</span>
</pre></div>
</div>
<ol class="arabic">
<li><p class="first">The necessary import.</p>
</li>
<li><p class="first">Defining a test function; the name of this function <strong>must</strong>
start with <code class="docutils literal notranslate"><span class="pre">test_</span></code>.</p>
</li>
<li><p class="first">Depending on whether the test is run with all the others by pytest
or whether it is run as a single test, we need to import the
file raising the exception differently.</p>
</li>
<li><p class="first">While friendly_traceback can be installed “globally”, as an
exception hook, we use it instead in a localized try/except
statement.</p>
</li>
<li><p class="first">By default, friendly_traceback outputs its result to sys.stderr.
However, this can be redirected to any other user provided
function. In addition, there is a “capture” mode, as indicated,
which simply stores the result.</p>
</li>
<li><p class="first">To retrieve the previously stored result, we use the
<code class="docutils literal notranslate"><span class="pre">get_output()</span></code> method. By default, this method also empties
the cache used to capture the output. There is an optional
argument to change this behaviour but it would be counter
productive in this situation as we wish our tests to be done
independently.</p>
</li>
<li><p class="first">Pytest checks for assertion errors. So, we include parts of
what we expect to see in the output. This is usually the
beginning of the line just below <code class="docutils literal notranslate"><span class="pre">Python</span> <span class="pre">exception:</span></code> that
was shown when running something like <code class="docutils literal notranslate"><span class="pre">raise_myexception.py</span></code>
previously. For reliability, we should include more than
just the name of the Exception.</p>
</li>
<li><p class="first">We must return the previously captured result for independent
testing.</p>
</li>
<li><p class="first">By adding this, we can run something like:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">python</span> <span class="n">tests</span><span class="o">/</span><span class="n">catch_name_error</span><span class="o">.</span><span class="n">py</span>
</pre></div>
</div>
<p>and see the expected result.</p>
</li>
</ol>
</div>
</div>
<div class="section" id="adding-generic-information">
<h2>Adding generic information<a class="headerlink" href="#adding-generic-information" title="Permalink to this headline">¶</a></h2>
<p>The main goal of friendly_tracebacks is to help beginners and/or
programmers whose knowledge of English is limited,
to understand more easily what a given exception means.
So, your first goal is to imagine that you are helping a beginner
understand what SomeException means, writing in English with
as little Python-specific jargon as possible.  Try to do
so in a short paragraph. Do not strive for perfection.
It is expected that we will hear from actual users
(teachers and students) using friendly_tracebacks and that we
will be able to improve the descriptions based on their feedback,
and not based on our own pre-conception.</p>
<p>Generic information about given exceptions is found in file
<code class="docutils literal notranslate"><span class="pre">friendly_traceback/generic_info.py</span></code>.
Here are the relevant parts of that file for the NameError
exception:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">name_error</span><span class="p">(</span><span class="o">*</span><span class="n">args</span><span class="p">):</span>
    <span class="n">_</span> <span class="o">=</span> <span class="n">current_lang</span><span class="o">.</span><span class="n">lang</span>
    <span class="k">return</span> <span class="n">_</span><span class="p">(</span>
        <span class="s2">&quot;    A NameError exception indicates that a variable or</span><span class="se">\n</span><span class="s2">&quot;</span>
        <span class="s2">&quot;    function name is not known to Python.</span><span class="se">\n</span><span class="s2">&quot;</span>
        <span class="s2">&quot;    Most often, this is because there is a spelling mistake.</span><span class="se">\n</span><span class="s2">&quot;</span>
        <span class="s2">&quot;    However, sometimes it is because the name is used</span><span class="se">\n</span><span class="s2">&quot;</span>
        <span class="s2">&quot;    before being defined or given a value.</span><span class="se">\n</span><span class="s2">&quot;</span>
    <span class="p">)</span>


<span class="n">generic</span> <span class="o">=</span> <span class="p">{</span>
    <span class="s2">&quot;IndentationError&quot;</span><span class="p">:</span> <span class="n">indentation_error</span><span class="p">,</span>
    <span class="s2">&quot;NameError&quot;</span><span class="p">:</span> <span class="n">name_error</span><span class="p">,</span>
    <span class="s2">&quot;SyntaxError&quot;</span><span class="p">:</span> <span class="n">syntax_error</span><span class="p">,</span>
    <span class="s2">&quot;Unknown&quot;</span><span class="p">:</span> <span class="n">unknown</span><span class="p">,</span>
<span class="p">}</span>
</pre></div>
</div>
<p>We use gettext for providing translations. You do not need to be
familiar with gettext for this doing this work.
For those that are familiar with gettext, the most common way
to use it is to <strong>install</strong> it globally, so that the function <code class="docutils literal notranslate"><span class="pre">_</span></code>
is added to Python’s builtins and can be used everywhere.
For reasons that will be explained elsewhere, we cannot do this
in this project.</p>
<div class="admonition-todo admonition" id="index-0">
<p class="first admonition-title">Todo</p>
<p class="last">Explain why we do not install gettext globally.</p>
</div>
<p>We first define a function whose name reflects the exception
we wish to explain. Thus, for <code class="docutils literal notranslate"><span class="pre">NameError</span></code>,
we defined <code class="docutils literal notranslate"><span class="pre">name_error()</span></code>.
This function will receive some positional arguments that may be useful for some exceptions.  For the first run through, you can
assume that you can ignore these arguments.</p>
<p>Ideally, this function should be inserted sorted alphabetically
in the file.</p>
<p>The first line of the function is:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">_</span> <span class="o">=</span> <span class="n">current_lang</span><span class="o">.</span><span class="n">lang</span>
</pre></div>
</div>
<p>This ensures that translations done by gettext are handled correctly.</p>
<p>Next, we return a string enclosed by <code class="docutils literal notranslate"><span class="pre">_(</span> <span class="pre">)</span></code>; this is a call to
gettext to retrieve the correct translation.</p>
<p>For clarity, instead of using triple-quoted strings, we use Python’s
automatic concatenation of adjacent strings to format the text.
Experience has shown us that this makes it much easier to
write the corresponding translations using Poedit.
Each string should represent a single line of text, and end with
a single <code class="docutils literal notranslate"><span class="pre">\n</span></code>.
In addition, each line should be indented by four spaces.
The latter both makes it easier to read the explanation when using
an REPL, and allows for automatic embedding with correct formatting
in the documentation using Sphinx.</p>
<p>Finally, at the very bottom of that file, you need to add an
entry to the dict of the form:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="s2">&quot;MyException&quot;</span><span class="p">:</span> <span class="n">my_exception</span><span class="p">,</span>
</pre></div>
</div>
<p>This entry should be added so as to respect the alphabetical order
used.</p>
</div>
<div class="section" id="add-specific-information">
<h2>Add specific information<a class="headerlink" href="#add-specific-information" title="Permalink to this headline">¶</a></h2>
<p>Let’s look again at the output for NameError.
At the top of the feedback given by friendly_traceback, we
see the following:</p>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    NameError: name &#39;c&#39; is not defined
</pre></div>
</div>
<p>The second line is the information given by Python.
Your goal should be to rephrase this information in a way that
is possibly easier to understand by beginners <strong>and</strong> which can
be translated into languages other than English.
It should also follow naturally from your generic information.</p>
<p>In some cases, such as <code class="docutils literal notranslate"><span class="pre">SyntaxError</span></code>, we might need the actual
source code in order to provide some very specific information.
For now, we assume that this is not the case.</p>
<p>Examining the line <code class="docutils literal notranslate"><span class="pre">NameError:</span> <span class="pre">name</span> <span class="pre">'c'</span> <span class="pre">is</span> <span class="pre">not</span> <span class="pre">defined</span></code>, we
see that it refers to a variable name, <code class="docutils literal notranslate"><span class="pre">c</span></code>, which will almost
certainly be different when another user encounters a similar error.
Thus, our specific information should include this as a variable.</p>
<p>Specific information about given exceptions is found in file
<code class="docutils literal notranslate"><span class="pre">friendly_traceback/specific_info.py</span></code>.
Here are the relevant parts of that file for the NameError
exception:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">name_error</span><span class="p">(</span><span class="n">etype</span><span class="p">,</span> <span class="n">value</span><span class="p">):</span>
    <span class="n">_</span> <span class="o">=</span> <span class="n">current_lang</span><span class="o">.</span><span class="n">lang</span>
    <span class="c1"># value is expected to be something like</span>
    <span class="c1">#</span>
    <span class="c1"># NameError: name &#39;c&#39; is not defined</span>
    <span class="c1">#</span>
    <span class="c1"># By splitting value using &#39;, we can extract the variable name.</span>
    <span class="k">return</span> <span class="n">_</span><span class="p">(</span><span class="s2">&quot;        In your program, the unknown name is &#39;</span><span class="si">{var_name}</span><span class="s2">&#39;.</span><span class="se">\n</span><span class="s2">&quot;</span><span class="p">)</span><span class="o">.</span><span class="n">format</span><span class="p">(</span>
        <span class="n">var_name</span><span class="o">=</span><span class="nb">str</span><span class="p">(</span><span class="n">value</span><span class="p">)</span><span class="o">.</span><span class="n">split</span><span class="p">(</span><span class="s2">&quot;&#39;&quot;</span><span class="p">)[</span><span class="mi">1</span><span class="p">]</span>
    <span class="p">)</span>

<span class="n">get_cause</span> <span class="o">=</span> <span class="p">{</span>
    <span class="s2">&quot;IndentationError&quot;</span><span class="p">:</span> <span class="n">indentation_error</span><span class="p">,</span>
    <span class="s2">&quot;NameError&quot;</span><span class="p">:</span> <span class="n">name_error</span><span class="p">,</span>
    <span class="s2">&quot;SyntaxError&quot;</span><span class="p">:</span> <span class="n">syntax_error</span><span class="p">,</span>
<span class="p">}</span>
</pre></div>
</div>
<p>I assume that this is similar enough to the situation for the
generic information case that it does not warrant additional
explanation.  <strong>The only difference is that each line of text should
be indented by 8 spaces.</strong></p>
<p>If you find that some additional explanation is needed,
please contact us or file an issue.</p>
</div>
<div class="section" id="test-your-work">
<h2>Test your work<a class="headerlink" href="#test-your-work" title="Permalink to this headline">¶</a></h2>
<p>Now that you have added the generic and specific information,
you should test again by running something like:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">python</span> <span class="n">tests</span><span class="o">/</span><span class="n">raise_my_exception</span><span class="o">.</span><span class="n">py</span>
<span class="n">python</span> <span class="n">tests</span><span class="o">/</span><span class="n">catch_my_exception</span><span class="o">.</span><span class="n">py</span>
</pre></div>
</div>
<p>and confirm, in both cases that the result is acceptable.</p>
<p>Once this is done, run pytest from the root directory to make
sure that your new case is included in the test suite.</p>
</div>
<div class="section" id="make-a-pull-request">
<h2>Make a pull request<a class="headerlink" href="#make-a-pull-request" title="Permalink to this headline">¶</a></h2>
<p>Before submitting your code, you should make sure that it
is formatted correctly according to <a class="reference external" href="https://github.com/ambv/black">black</a></p>
<p>However, we ask that you ensures that your added text
uses the one-line-per-string format described above.
If black reformats your code such that this is not the case, you
can temporarily turn it off and back on around the relevant
code.  Here’s an example that we currently have in our code:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="c1"># fmt: off</span>
<span class="k">return</span> <span class="n">_</span><span class="p">(</span>
    <span class="s2">&quot;</span><span class="se">\n</span><span class="s2">&quot;</span>
    <span class="s2">&quot;    Python exception: </span><span class="se">\n</span><span class="s2">&quot;</span>
    <span class="s2">&quot;        </span><span class="si">{name}</span><span class="s2">: </span><span class="si">{value}</span><span class="se">\n</span><span class="s2">&quot;</span>
    <span class="s2">&quot;</span><span class="se">\n</span><span class="s2">&quot;</span>
    <span class="s2">&quot;</span><span class="si">{explanation}</span><span class="s2">&quot;</span>
<span class="p">)</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="n">name</span><span class="p">,</span> <span class="n">value</span><span class="o">=</span><span class="n">value</span><span class="p">,</span> <span class="n">explanation</span><span class="o">=</span><span class="n">explanation</span><span class="p">)</span>
<span class="c1"># fmt: on</span>
</pre></div>
</div>
<p>Next, you should make sure that your local repository is up to date
and fix any conflict that might be arising.</p>
<p>Finally, you can proceed with a <a class="reference external" href="https://help.github.com/en/articles/creating-a-pull-request">pull request</a>.
If the information provided in that link is not clear, please do
not hesitate to ask for clarification.</p>
</div>
<div class="section" id="adding-to-an-existing-exception">
<h2>Adding to an existing exception<a class="headerlink" href="#adding-to-an-existing-exception" title="Permalink to this headline">¶</a></h2>
<div class="admonition-todo admonition" id="index-1">
<p class="first admonition-title">Todo</p>
<p class="last">To be written</p>
</div>
</div>
</div>


          </div>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="tracebacks_en.html" title="Friendly tracebacks - in English"
             >next</a> |</li>
        <li class="right" >
          <a href="design.html" title="Some thoughts on the design of friendly-traceback"
             >previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="index.html">Friendly tracebacks 0.0.3 documentation</a> &#187;</li> 
      </ul>
    </div>
    <div class="footer" role="contentinfo">
        &#169; Copyright 2019, André Roberge.
      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.8.4.
    </div>
  </body>
</html>