
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Friendly tracebacks - in English &#8212; Friendly tracebacks 0.0.4 documentation</title>
    <link rel="stylesheet" href="_static/sphinxdoc.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    <script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <script type="text/javascript" src="_static/language_data.js"></script>
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
    <link rel="next" title="Friendly SyntaxError tracebacks - in English" href="syntax_tracebacks_en.html" />
    <link rel="prev" title="Dealing with Syntax Errors" href="syntax_error.html" /> 
  </head><body>
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="syntax_tracebacks_en.html" title="Friendly SyntaxError tracebacks - in English"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="syntax_error.html" title="Dealing with Syntax Errors"
             accesskey="P">previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="index.html">Friendly tracebacks 0.0.4 documentation</a> &#187;</li> 
      </ul>
    </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
  <h3><a href="index.html">Table of Contents</a></h3>
  <ul>
<li><a class="reference internal" href="#">Friendly tracebacks - in English</a><ul>
<li><a class="reference internal" href="#indentationerror-1-expected-an-indented-block">IndentationError - 1: expected an indented block</a></li>
<li><a class="reference internal" href="#indentationerror-2-unexpected-indent">IndentationError - 2: unexpected indent</a></li>
<li><a class="reference internal" href="#indentationerror-3-unindent-does-not-match">IndentationError - 3: unindent does not match …</a></li>
<li><a class="reference internal" href="#nameerror">NameError</a></li>
<li><a class="reference internal" href="#syntaxerror">SyntaxError</a></li>
<li><a class="reference internal" href="#taberror-1">TabError - 1</a></li>
<li><a class="reference internal" href="#taberror-2">TabError - 2</a></li>
<li><a class="reference internal" href="#unboundlocalerror">UnboundLocalError</a></li>
<li><a class="reference internal" href="#unknown-exception">Unknown exception</a></li>
<li><a class="reference internal" href="#zerodivisionerror-1">ZeroDivisionError - 1</a></li>
<li><a class="reference internal" href="#zerodivisionerror-2">ZeroDivisionError - 2</a></li>
</ul>
</li>
</ul>

  <h4>Previous topic</h4>
  <p class="topless"><a href="syntax_error.html"
                        title="previous chapter">Dealing with Syntax Errors</a></p>
  <h4>Next topic</h4>
  <p class="topless"><a href="syntax_tracebacks_en.html"
                        title="next chapter">Friendly SyntaxError tracebacks - in English</a></p>
  <div role="note" aria-label="source link">
    <h3>This Page</h3>
    <ul class="this-page-menu">
      <li><a href="_sources/tracebacks_en.rst.txt"
            rel="nofollow">Show Source</a></li>
    </ul>
   </div>
<div id="searchbox" style="display: none" role="search">
  <h3>Quick search</h3>
    <div class="searchformwrapper">
    <form class="search" action="search.html" method="get">
      <input type="text" name="q" />
      <input type="submit" value="Go" />
      <input type="hidden" name="check_keywords" value="yes" />
      <input type="hidden" name="area" value="default" />
    </form>
    </div>
</div>
<script type="text/javascript">$('#searchbox').show(0);</script>
        </div>
      </div>

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body" role="main">
            
  <div class="section" id="friendly-tracebacks-in-english">
<h1>Friendly tracebacks - in English<a class="headerlink" href="#friendly-tracebacks-in-english" title="Permalink to this headline">¶</a></h1>
<p>Friendly-traceback aims to provide friendlier feedback when an exception
is raised than what is done by Python.
Below, we can find some examples. SyntaxError cases are
shown in a separate page.
Ideally, an example of each case handled by friendly-traceback
should be included here.</p>
<div class="admonition note">
<p class="first admonition-title">Note</p>
<p class="last">The content of this page is generated by running
trb_english.py located in the <code class="docutils literal notranslate"><span class="pre">tests/</span></code> directory.
This needs to be done explicitly, independently of updating the
documentation using Sphinx.
On Windows, if Sphinx is installed on your computer, it is suggested
instead to run make_tb.bat in the root directory as it will create
similar files for all languages <em>and</em> update the documentation.</p>
</div>
<p>Friendly-traceback version: 0.0.4
Python version: 3.7.0</p>
<div class="section" id="indentationerror-1-expected-an-indented-block">
<h2>IndentationError - 1: expected an indented block<a class="headerlink" href="#indentationerror-1-expected-an-indented-block" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    IndentationError: expected an indented block (raise_indentation_error1.py, line 4)

An IndentationError occurs when a given line of code is
not indented (aligned vertically with other lines) as expected.

Likely cause:
    Python could not parse the file &#39;raise_indentation_error1.py&#39;
    beyond the location indicated below by --&gt; and ^.

   1: &#39;&#39;&#39;Should raise IndentationError&#39;&#39;&#39;
   2:
   3: if True:
--&gt;4: pass
         ^
    In this case, the line identified above
    was expected to begin a new indented block.
</pre></div>
</div>
</div>
<div class="section" id="indentationerror-2-unexpected-indent">
<h2>IndentationError - 2: unexpected indent<a class="headerlink" href="#indentationerror-2-unexpected-indent" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    IndentationError: unexpected indent (raise_indentation_error2.py, line 4)

An IndentationError occurs when a given line of code is
not indented (aligned vertically with other lines) as expected.

Likely cause:
    Python could not parse the file &#39;raise_indentation_error2.py&#39;
    beyond the location indicated below by --&gt; and ^.

   1: &#39;&#39;&#39;Should raise IndentationError&#39;&#39;&#39;
   2: if True:
   3:     pass
--&gt;4:       pass
           ^
    In this case, the line identified above
    is more indented than expected and
    does not match the indentation of the previous line.
</pre></div>
</div>
</div>
<div class="section" id="indentationerror-3-unindent-does-not-match">
<h2>IndentationError - 3: unindent does not match …<a class="headerlink" href="#indentationerror-3-unindent-does-not-match" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    IndentationError: unindent does not match any outer indentation level (raise_indentation_error3.py, line 4)

An IndentationError occurs when a given line of code is
not indented (aligned vertically with other lines) as expected.

Likely cause:
    Python could not parse the file &#39;raise_indentation_error3.py&#39;
    beyond the location indicated below by --&gt; and ^.

   1: &#39;&#39;&#39;Should raise IndentationError&#39;&#39;&#39;
   2: if True:
   3:       pass
--&gt;4:     pass
              ^
    In this case, the line identified above is
    less indented than the preceding one,
    and is not aligned vertically with another block of code.
</pre></div>
</div>
</div>
<div class="section" id="nameerror">
<h2>NameError<a class="headerlink" href="#nameerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    NameError: name &#39;c&#39; is not defined

A NameError exception indicates that a variable or
function name is not known to Python.
Most often, this is because there is a spelling mistake.
However, sometimes it is because the name is used
before being defined or given a value.

Likely cause:
    In your program, the unknown name is &#39;c&#39;.


Execution stopped on line 7 of file &#39;test_name_error.py&#39;.

   5: def test_name_error():
   6:     try:
--&gt;7:         b = c
   8:     except Exception:
</pre></div>
</div>
</div>
<div class="section" id="syntaxerror">
<h2>SyntaxError<a class="headerlink" href="#syntaxerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    SyntaxError: invalid syntax (raise_syntax_error1.py, line 3)

A SyntaxError occurs when Python cannot understand your code.
There could be many possible reasons:
- a keyword might be misspelled;
- a colon, :, or some other symbol like (, ], etc., might be missing;
- etc.

Likely cause:
    Python could not parse the file &#39;raise_syntax_error1.py&#39;
    beyond the location indicated below by --&gt; and ^.

   1: &quot;&quot;&quot; Should raise SyntaxError&quot;&quot;&quot;
   2:
--&gt;3: pass = 2
           ^
    My best guess: you were trying to assign a value
    to a Python keyword. This is not allowed.
</pre></div>
</div>
</div>
<div class="section" id="taberror-1">
<h2>TabError - 1<a class="headerlink" href="#taberror-1" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TypeError: &#39;module&#39; object is not callable

No information is known about this exception.


Execution stopped on line 51 of file &#39;trb_common.py&#39;.

   49:                     mod = __import__(name)
   50:                     if function is not None:
--&gt;51:                         result = getattr(mod, function)()
   52:                         write(result)
</pre></div>
</div>
</div>
<div class="section" id="taberror-2">
<h2>TabError - 2<a class="headerlink" href="#taberror-2" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    TabError: inconsistent use of tabs and spaces in indentation (raise_tab_error2.py, line 7)

A TabError indicates that you have used both spaces
and tab characters to indent your code.
This is not allowed in Python.
Indenting your code means to have block of codes aligned vertically
by inserting either spaces or tab characters at the beginning of lines.
Python&#39;s recommendation is to always use spaces to indent your code.

Likely cause:
    Python could not parse the file &#39;raise_tab_error2.py&#39;
    beyond the location indicated below by --&gt; and ^.

    4:
    5: def no_pytest_tab_error2():
    6:     if True:
--&gt; 7:      pass
            ^
</pre></div>
</div>
</div>
<div class="section" id="unboundlocalerror">
<h2>UnboundLocalError<a class="headerlink" href="#unboundlocalerror" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    UnboundLocalError: local variable &#39;a&#39; referenced before assignment

In Python, variables that are used inside a function are known as
local variables. Before they are used, they must be assigned a value.
A variable that is used before it is assigned a value is assumed to
be defined outside that function; it is known as a &#39;global&#39;
(or sometimes &#39;nonlocal&#39;) variable. You cannot assign a value to such
a global variable inside a function without first indicating to
Python that this is a global variable, otherwise you will see
an UnboundLocalError.

Likely cause:
    The variable that appears to cause the problem is &#39;a&#39;.
    Try inserting the statement
        global a
    as the first line inside your function.

Execution stopped on line 13 of file &#39;test_unbound_local_error.py&#39;.

   11:
   12:     try:
--&gt;13:         inner()
   14:     except Exception:


Exception raised on line 10 of file &#39;test_unbound_local_error.py&#39;.

    8:
    9:     def inner():
--&gt;10:         a += 1
   11:
</pre></div>
</div>
</div>
<div class="section" id="unknown-exception">
<h2>Unknown exception<a class="headerlink" href="#unknown-exception" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    MyException: Some informative message

No information is known about this exception.


Execution stopped on line 11 of file &#39;test_unknown_error.py&#39;.

    9: def test_unknown_error():
   10:     try:
--&gt;11:         raise MyException(&quot;Some informative message&quot;)
   12:     except Exception:
</pre></div>
</div>
</div>
<div class="section" id="zerodivisionerror-1">
<h2>ZeroDivisionError - 1<a class="headerlink" href="#zerodivisionerror-1" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    ZeroDivisionError: division by zero

A ZeroDivisionError occurs when you are attempting to divide
a value by zero:
    result = my_variable / 0
It can also happen if you calculate the remainder of a division
using the modulo operator &#39;%&#39;
    result = my_variable % 0

Execution stopped on line 7 of file &#39;test_zero_division_error.py&#39;.

   5: def test_zero_division_error():
   6:     try:
--&gt;7:         1 / 0
   8:     except Exception:
</pre></div>
</div>
</div>
<div class="section" id="zerodivisionerror-2">
<h2>ZeroDivisionError - 2<a class="headerlink" href="#zerodivisionerror-2" title="Permalink to this headline">¶</a></h2>
<div class="highlight-none notranslate"><div class="highlight"><pre><span></span>Python exception:
    ZeroDivisionError: integer division or modulo by zero

A ZeroDivisionError occurs when you are attempting to divide
a value by zero:
    result = my_variable / 0
It can also happen if you calculate the remainder of a division
using the modulo operator &#39;%&#39;
    result = my_variable % 0

Execution stopped on line 17 of file &#39;test_zero_division_error.py&#39;.

   15: def test_zero_division_error2():
   16:     try:
--&gt;17:         1 % 0
   18:     except Exception:
</pre></div>
</div>
</div>
</div>


          </div>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="syntax_tracebacks_en.html" title="Friendly SyntaxError tracebacks - in English"
             >next</a> |</li>
        <li class="right" >
          <a href="syntax_error.html" title="Dealing with Syntax Errors"
             >previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="index.html">Friendly tracebacks 0.0.4 documentation</a> &#187;</li> 
      </ul>
    </div>
    <div class="footer" role="contentinfo">
        &#169; Copyright 2019, André Roberge.
      Created using <a href="http://sphinx-doc.org/">Sphinx</a> 1.8.4.
    </div>
  </body>
</html>